### ISSUE TITLE
Clarification on shipping pre-built releases in proprietary applications

### ISSUE THREAD

**Issue by estan** [ShiftMediaProject/fontconfig#1]
Hi all,

Thanks a lot for providing this!

Quick question: The README states that all ShiftMediaProject original code is licensed under GPLv2 (while the original fontconfig code of course is under their license). Does this mean I cannot take the pre-built releases available here on GitHub Releases and ship it as part of my closed source proprietary application? (since I would need to comply with the terms of GPLv2).

**Comment by Sibras** [comment]
I am in the process of updating the readme's to fix that as its not properly stated correctly. But the binaries are provided under the original projects license terms so in this case they have the original fontconfig license.

All the applicable licenses for the binaries are provided with each binary release under the licenses sub folder found in each download archive. These are the only licenses that are applicable for the binary releases and are the original projects (aswell as any dependency projects) unmodified licenses.

**Comment by estan** [comment]
Thanks for the clarification @Sibras!
