### ISSUE TITLE
Questions about build types of libraries & how to build it

### ISSUE THREAD

**Issue by qwer6019** [ShiftMediaProject/fontconfig#2]
Hello, thanks for providing and maintaining fontconfig for Window versions.

Could you let me know the libraries(.dll & .lib) you uploaded are built by release mode? or debug mode?
(libfontconfig_2.13.1-4_msvc16.zip, at https://github.com/ShiftMediaProject/fontconfig/releases)

And I also tried few days to build by myself using 'Source code(zip)', but failed from the first when i executed 'autoconf'.
Is it the right way? Otherwise please let me know how to build it.

Thanks.

* Version Used: 2.13.1-4_msvc16.zip
* Operating System and Version: Window10
* Compiler and Version(s): Visual Studio 2019

**Comment by Sibras** [comment]
> Could you let me know the libraries(.dll & .lib) you uploaded are built by release mode? or debug mode?

The released binaries are built in release mode.

> Is it the right way? Otherwise please let me know how to build it.

Nope. This project contains visual studio project files within the SMP folder that can be used to build from source.

**Comment by qwer6019** [comment]
Thanks for your help :)
